const data = {
    products: [
      {
       _id:'1',
        name: 'Paola Bed 180x200 Cm Black',
        slug: 'Paola Bed 180x200 Cm Black',
        category: 'Beds',
        image: '/images/bed1.jpg', // 679px × 829px
        price: 850,
        countInStock: 10,
        brand: 'Paola',
        rating: 4.5,
        numReviews: 10,
        description: ' Product Details : Material- Mdf, Secondary Material: MetalColor: Black, Features: Panel,Metal Essence Mattress Size: 180X200 CM Weight(KG): 77 Size : KING Care Instruction: Wipe clean with a soft, dry cloth'
      },
      {
        _id:'2',
        name: ' Lederberg Dressing Table With Mirror',
        slug: 'Lederberg Dressing Table With Mirror',
        category: 'Dressing Table',
        image: '/images/dressing1.jpg',
        price: 1580,
        countInStock: 0,
        brand: 'Lederberg',
        rating: 4.0,
        numReviews: 10,
        description: ' Material: Mdf Secondary Material: Glass Color: Silver Features: Drawers,Storage Specific: mirror finish Weight(KG): 139 Care Instruction: Wipe clean with a soft, dry cloth.',
      },
      {
       _id:'3',
        name: 'Aberton 6 Door Wardrobe',
        slug: 'Aberton 6 Door Wardrobe',
        category: 'Wardrobe',
        image: '/images/wardrobe2.jpg',
        price: 2559,
        countInStock: 15,
        brand: 'Aberton',
        rating: 4.5,
        numReviews: 14,
        description: '1 - 6 Door Wardrobe    275 cm L x 68 cm W x 225 cm H Material: Mdf Secondary Material: Glass Color: Black Features: Drawers,Storage,Shelves,Led Lights Specific: Mirror Weight(KG): 295 Care Instruction: Wipe clean with a soft, dry cloth.',
      },
      {
      _id:'4',
        name: ' Rainey Bed 200x210 Cm',
        slug: 'Rainey Bed 200x210 Cm',
        category: 'Beds',
        image: '/images/bed2.jpg',
        price: 6550,
        countInStock: 5,
        brand: 'Rainey',
        rating: 4.5,
        numReviews: 10,
        description: ' Product Details : Material- Mdf, Secondary Material: MetalColor: Black, Features: Panel,Metal Essence Mattress Size: 180X200 CM Weight(KG): 77 Size : KING Care Instruction: Wipe clean with a soft, dry cloth ',
      },
      {
        _id:'5',
         name: 'Helix Dresser W / Mirror',
         slug: 'Helix Dresser W / Mirror',
         category: 'Dressing ',
         image: '/images/dressing2.jpg', // 679px × 829px
         price: 120,
         countInStock: 10,
         brand: 'Helix',
         rating: 4.5,
         numReviews: 10,
         description: '  1 - Dressing Table With Mirror    157 cm L x 47 cm W x 182 cm H   Material: Mdf Color: Beige Features: Drawers,Storage Weight(KG): 109 Care Instruction: Wipe clean with a soft, dry cloth.',
       },
       {
         _id:'6',
         name: 'Riddleville Sectional Sofa',
         slug: 'Riddleville Sectional Sofa',
         category: 'Shirts',
         image: '/images/sofa1.jpg',
         price: 8590,
         countInStock: 5,
         brand: 'Riddleville',
         rating: 4.0,
         numReviews: 10,
         description: ' Grace your interior with the charm of curvy lines by bringing home our RIDDLEVILLE SECTIONAL SOFA. Designed in a curved outline, this velvety sofa with plush padding and a smooth finish offers you a luxurious seating experience. The two sections can be easily moved around and arranged anywhere in your home, making it a versatile choice. The gold-finished metal legs set against its neutral tone and the diamond-stitched detailing along its back add a striking statement to this beauty.',
       },
       {
        _id:'7',
         name: 'Claudius 3 Door Sliding Wardrobe',
         slug: 'Claudius 3 Door Sliding Wardrobe',
         category: 'wardrobe',
         image: '/images/r3.jpg',
         price: 7896,
         countInStock: 15,
         brand: 'Claudius  ',
         rating: 4.5,
         numReviews: 14,
         description: ' CLAUDIUS 3 DOOR SLIDING WARDROBE will create a glamorous look to your master suite. Crafted from MDF board, this grand wardrobe features 3 doors that slide open to reveal a hanging rod on either sides and an array of drawers and shelves in the middle. The mirrored front creates an illusion of space, increases lightening and most importantly allows you to check your look before taking on the day.',
       },
       {
       _id:'8',
         name: ' Castries Bed 200x200 Cm',
         slug: 'Castries Bed 200x200 Cm',
         category: 'Beds',
         image: '/images/bed3.jpg',
         price: 2598,
         countInStock: 5,
         brand: 'Castries',
         rating: 4.5,
         numReviews: 10,
         description: ' Product Description - Set a glamorous tone in your master bedroom with CASTRIES BED. Crafted with metal, this chic canopy bed features chrome finish posters for a touch of luxe. Upholstered in soft velvet fabric, its tall headboard has padded panels to lend comfort and elegance to your bedroom. Its fine quality structure assures longevity. With its streamlined and polished design, this bed creates a perfect focal point in your modern interior. Dimensions Bed 200x200    217 cm L x 211 cm W x 211 cm H',
       }
    ]
  };
  export default data;